### PR TITLE
Vectorized time stamp processing

### PR DESCRIPTION
**Pull request by lemire**
Fixes https://github.com/NLnetLabs/simdzone/issues/22

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
Thanks @lemire! Most of this looks good. There's a very noticable speedup. I add some tests and noticed the handling of Febuary 29 is off? It throws an error for Febuary 29 2024.

**Comment by lemire** [comment]
>  I added some tests and noticed the handling of Febuary 29 is off? It throws an error for Febuary 29 2024.

Does it? Let me see.

**Comment by lemire** [comment]
(The new version is called `sse_parse_time_alt` and it relies on a slightly different strategy.)

**Comment by k0ekk0ek** [comment]
Newer version indeed seems somewhat faster (2.24GB/s vs 2.30GB/s) on my laptop

**Comment by lemire** [comment]
> Newer version indeed seems somewhat faster (2.24GB/s vs 2.30GB/s) on my laptop

I will update the PR accordingly.

**Comment by lemire** [comment]
I have updated the code.

As you can see, I did write rather extensive tests.

**Comment by k0ekk0ek** [comment]
I think it's a bad test on my part.

**Comment by lemire** [comment]
@k0ekk0ek It is cool that we can reach and surpass 2 GB/s. :-)

**Comment by k0ekk0ek** [comment]
Indeed it was. I left the expected result at syntax error, while obviously for a leap year it is not an error. (Sorry :sweat:)

**Review by k0ekk0ek — APPROVED** [review]

**Comment by k0ekk0ek** [comment]
> @k0ekk0ek It is cool that we can reach and surpass 2 GB/s. :-)

Absolutely! Time stamps will certainly not be a bottleneck :slightly_smiling_face:

**Comment by k0ekk0ek** [comment]
I've merged. The test doesn't build on Windows (don't know why GH didn't update the PR, I've pushed), but I'll take care of that in a separate PR

**Comment by lemire** [comment]
> The test doesn't build on Windows

I did not build under Visual Studio. However, if there is an issue, it should be minor.

**Pull request merged**
